name: FTP Test
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: toupload
      # - run: echo "ls" | ftp ${{ env.FTP_USER_NAME }}:${{ env.FTP_USER_PASS }}@ftp-server/ftp
      # - name: file*delete.md
      #   uses: ./.github/actions/ftp-delete-action
      #   with:
      #     host: ftp-server
      #     user: ${{ env.FTP_USER_NAME }}
      #     password: ${{ env.FTP_USER_PASS }}
      #     workingDir: data
      #     ignoreSsl: 1
      #     remoteFiles: "file*.!(keep).md"


           
